image: Visual Studio 2017
build: off

environment:
  python_37: C:/Python37/python.exe

install:
  - "%python_37% -V"
  - "%python_37% -m pip install -e ."

test_script:
  - "%python_37% -m unittest"
